apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-resource-deploy
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          requests: # 최소
            memory: "250Mi"
            cpu: "250m"
          limits: # 최대
            memory: "500Mi"
            cpu: "1"
