apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: LoadBalancer
#  externalIPs:
#  - 10.178.0.4
  selector:
    app: blue-deployment
    # app: green-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
