apiVersion: v1
kind: Service
metadata:
  name: update-service
spec:
  type: LoadBalancer
#  externalIPs:
#  - 10.178.0.5
  selector:
    app: web-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
